# Generated by Django 2.2.19 on 2021-06-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proteina', 'Proteina'), ('frutas', 'Frutas'), ('legumes', 'Legumes')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryIngredientes.Categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descricao', models.TextField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveryIngredientes.Ingredientes', verbose_name='Ingredientes')),
            ],
        ),
    ]
